### ISSUE TITLE
Pytorch

### ISSUE THREAD

**Issue by FilipAndersson245** [YanaiEliyahu/AdasOptimizer#1]
This project looks cool, will you add PyTorch support in the future?

**Comment by YanaiEliyahu** [comment]
Yep, I already started writing one.

**Comment by YanaiEliyahu** [comment]
https://github.com/YanaiEliyahu/AdasOptimizer/blob/master/adasopt_pytorch.py

In my own testing it works OK.
How does it work for you?

**Comment by FilipAndersson245** [comment]
Will check it out when I get to my computer.

**Comment by FilipAndersson245** [comment]
It seems like Cuda is not properly set when running this code on the GPU,
adding `device="cuda:0` [here](https://github.com/YanaiEliyahu/AdasOptimizer/blob/5d431d1722585a2a6a05f381be85624ad2628ff9/adasopt_pytorch.py#L83) made it work temporary, but it can probably be set automatically depending on input device?

**Comment by FilipAndersson245** [comment]
> https://github.com/YanaiEliyahu/AdasOptimizer/blob/master/adasopt_pytorch.py
> 
> In my own testing it works OK.
> How does it work for you?

It seems like Cuda is not properly set when running this code on the GPU,
adding `device="cuda:0` [here](https://github.com/YanaiEliyahu/AdasOptimizer/blob/5d431d1722585a2a6a05f381be85624ad2628ff9/adasopt_pytorch.py#L83) made it work temporary, but it can probably be set automatically depending on input device?

**Comment by YanaiEliyahu** [comment]
does `,device=self._curr_var.device` also work for you?

**Comment by FilipAndersson245** [comment]
> does `,device=self._curr_var.device` also work for you?

Yes that seems to work

**Comment by YanaiEliyahu** [comment]
Great, I'll close this just for the protocol.
