### ISSUE TITLE
Pytorch - ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by demdecuong** [YanaiEliyahu/AdasOptimizer#2]
1st option:
I works for me if i use
`optimizer = Adas(model.parameters(), lr = config.lr)`

2nd option:
but not work if I use
`
  params = filter(lambda p: p.requires_grad, model.parameters())  `
 ` optimizer = Adas(params, lr = config.lr)`
It raise 'ValueError: optimizer got an empty parameter list' while traditional torch.optim is work with 2nd option.

Thank you for your amazing work.

Hope that you can update the pytorch script.

**Comment by sonvx** [comment]
@demdecuong It happens when model.parameters() is empty, you might try this to see if it works:

```
params = filter( lambda p: p.requires_grad, model.parameters() )
optimizer = Adas(list(params), lr = config.lr)
```

**Comment by demdecuong** [comment]
Thank you, the problem is fixed perfectly .
