### ISSUE TITLE
Tensorflow - AttributeError: 'AdasOptimizer' object has no attribute 'lr'

### ISSUE THREAD

**Issue by hoangtv8699** [YanaiEliyahu/AdasOptimizer#3]
it raise 'AttributeError: 'AdasOptimizer' object has no attribute 'lr'' when i try using ReduceLROnPlateau and run normaly when i stop using it. tried with tensorflow 2.3.1:

'''reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.8,
                                      patience=5, verbose=1, mode='auto', min_delta=0.0001, cooldown=5,
                                      min_lr=0.00001)'''

Thank you for your amazing work.

**Comment by YanaiEliyahu** [comment]
Unfortunately there is no good way to set the LR dynamically in Adas for the following reasons:

1. The `lr` parameter in the constructor is the **initial** LR of all first-order LRs.
2. The second-order LRs will raise the first-order LRs if the first-order LRs were lowered manually.
3. Lowering the first second and third order LRs will just make Adas like Adam without momentum.

Thank you for your sweet words!

**Comment by YanaiEliyahu** [comment]
I gave this ticket a second thought, Adas supposed to 100% automate LRs, do you wish to use this `reduce_lr` because Adas isn't doing a good job automating the LR? Think that would worth a ticket on its own.

**Comment by hoangtv8699** [comment]
Adas still work very well without ReduceLROnPlateau so you don't have to notice this. sorry for fotgot close this issue
